### Variáveis globais

@baseUrl = http://localhost:8080
@apiKey = {{createAccount.response.body.api_key}}

### Criar uma nova conta
# @name createAccount

POST {{baseUrl}}/accountS
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com"
}

### Obter dados da conta

GET {{baseUrl}}/accounts
X-API-KEY: {{apiKey}}
